---
- hosts: srv-web 
  vars_files:
          - vars/main.yml
  pre_tasks:
          - name: création de document client web
            file: 
             path: "{{ item.documentclient }}" 
             state: directory
            with_items: "{{ apache_vhosts }}"
  roles:
          - { role: geerlingguy.apache }
