---
- hosts: srv-db
  remote_user: root
  vars_files:
          - vars/main.yml

- name: Create Cron Dump SQL database
  cron:
    name: dump database {{item.name}} 
    minute: 30
    user: {{ mysql_users.name }}
    job: "/usr/bin/mysqldump --database {{ mysql_users.name }}/_db > {{ mysql_backup_dir.name }}/$(date)"
  with_items: {{ mysql_users }}