---
- hosts: srv-db
  remote_user: root
  #become: yes
  #become_user: root
  vars_files:
          - vars/main.yml
          #- /etc/ansible/roles/geerlingguy.mysql/vars/main.yml
  roles:
<<<<<<< HEAD
          - { role: geerlingguy.mysql }
=======
          - role: geerlingguy.mysql
>>>>>>> bb4db4374406765536c81a86190009c2681a81f4
          # - role: ome.mysql_backup
            # mysql_backup_dir: /var/backups/database
            # mysql_backup_filename_format: "{{ ansible_hostname }}-%Y%m%d.sql.gz"
            # mysql_backup_minimum_expected_size: 100000     
