---
packages:
        - htop
        - vim
        - git
        - ntpdate

user_group:
        - groupname: clientitescia

users:
        - username: client1
          password: itescia
          user_group: sudo, clientitescia
        - username: client2
          password: itescia
          user_group: sudo, clientitescia
        - username: client3
          password: itescia
          user_group: sudo, clientitescia
