---
- hosts: web 
  vars_files:
          - roles/vars/main.yml
  pre_tasks:
          - name: création de documentroot
            file: 
             path: "{{ item.documentroot }}" 
             state: directory
            with_items: "{{ apache_vhosts }}"
  roles:
          - { role: geerlingguy.apache }
